title: Canon
email: info@domain.com
description: Canon is coming soon. Sign up to be the first to know.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

social:
  instagram: https://www.instagram.com/thehoneyagency/
  facebook: https://www.facebook.com/thehoneyagency/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - Gruntfile.js
  - _sass