title: Canon
email: hello@canoneastsac.com
description: Welcome, grab a seat and stay awhile. Our chef-driven, seasonal tavern fare includes a canon of shareable bites, salads, entrées, craft-beers, spirits & wine. Trust us, its going to be amazing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://canoneastsac.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

social:
  # instagram: https://www.instagram.com/thehoneyagency/
  # facebook: https://www.facebook.com/thehoneyagency/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - Gruntfile.js
  - _sass


collections:    
  bios:
    output: true

social:
  01:
    name: 'facebook'
    link: ''
  02:
    name: 'twitter'
    link: 'https://twitter.com/CanonEastSac'
  03:
    name: 'instagram'
    link: 'https://www.instagram.com/canoneastsac/'
